"""Markdown renderer for the Onboarding Navigator."""
from __future__ import annotations

import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from cerebrofy.onboard.planner import OnboardPlan


def render_markdown(plan: OnboardPlan) -> str:
    """Produce the full ONBOARDING.md content."""
    sections = [
        _render_header(plan),
        _render_overview(plan),
        _render_team_context(plan),
        _render_reading_order(plan),
        _render_entry_points(plan),
        _render_hotspots(plan),
        _render_safe_zones(plan),
        _render_things_to_know(plan),
        _render_footer(plan),
    ]
    return "\n\n".join(s for s in sections if s)


def _render_header(plan: OnboardPlan) -> str:
    recipient = f", {plan.name}" if plan.name else ""
    ts = datetime.datetime.utcfromtimestamp(plan.generated_ts).strftime("%Y-%m-%d")
    focus = f" · focus: `{plan.focus_lobe}`" if plan.focus_lobe else ""
    lobe_count = len(plan.lobe_reading_order)
    return "\n".join([
        f"# Getting Started with `{plan.repo_name}`{focus}",
        "",
        f"Welcome{recipient}! This guide was auto-generated by Cerebrofy on {ts}.",
        f"Depth calibration for AI agents: **{plan.depth}**.",
        "",
        (
            f"**{plan.neuron_count}** functions/classes · "
            f"**{plan.edge_count}** call edges · "
            f"**{lobe_count}** modules"
        ),
    ])


def _render_overview(plan: OnboardPlan) -> str:
    if not plan.map_md_path:
        return ""
    try:
        with open(plan.map_md_path, encoding="utf-8") as f:
            content = f.read(3000).strip()
        if not content:
            return ""
        return "## What This Codebase Does\n\n" + content
    except OSError:
        return ""


def _render_team_context(plan: OnboardPlan) -> str:
    ctx = plan.team_context
    if not ctx:
        return ""
    lines = ["## 🎯 Team Context"]
    if "sprint_goal" in ctx:
        deadline = f" _(deadline: {ctx['sprint_deadline']})_" if "sprint_deadline" in ctx else ""
        lines += ["", f"**Sprint goal:** {ctx['sprint_goal']}{deadline}"]
    if "open_incidents" in ctx:
        lines += ["", "**Open incidents:**"]
        for inc in ctx["open_incidents"]:
            lines.append(f"- `[{inc['severity'].upper()}]` {inc['description']}")
    if "arch_direction" in ctx:
        lines += ["", f"**Architectural direction:** {ctx['arch_direction']}"]
    if "avoid_patterns" in ctx:
        lines += ["", "**Avoid:**"]
        for p in ctx["avoid_patterns"]:
            lines.append(f"- {p}")
    if "concerns" in ctx:
        lines += ["", "**Team concerns:**"]
        for c in ctx["concerns"]:
            lines.append(f"- {c}")
    return "\n".join(lines)


def _render_reading_order(plan: OnboardPlan) -> str:
    if not plan.lobe_reading_order:
        return ""
    lines = [
        "## Recommended Reading Order",
        "",
        "Read the modules in this order — each builds on the previous:",
        "",
    ]
    for i, lobe in enumerate(plan.lobe_reading_order, 1):
        if lobe.coupling_ratio < 0.2:
            badge = "🟢 low coupling"
        elif lobe.coupling_ratio < 0.5:
            badge = "🟡 medium coupling"
        else:
            badge = "🔴 high coupling"
        ep_note = ""
        if lobe.entry_point_count:
            plural = "s" if lobe.entry_point_count != 1 else ""
            ep_note = f", {lobe.entry_point_count} entry point{plural}"
        lines.append(
            f"{i}. **{lobe.name}/** `{lobe.directory}` "
            f"({lobe.neuron_count} neurons{ep_note}) — {badge}"
        )
    return "\n".join(lines)


def _render_entry_points(plan: OnboardPlan) -> str:
    if not plan.entry_points:
        return ""
    lines = [
        "## Entry Points (Where Execution Starts)",
        "",
        "| Function | File | Lobe |",
        "|---|---|---|",
    ]
    for ep in plan.entry_points:
        lines.append(f"| `{ep.name}` | `{ep.file}:{ep.line_start}` | {ep.lobe} |")
    return "\n".join(lines)


def _render_hotspots(plan: OnboardPlan) -> str:
    if not plan.hotspots:
        return ""
    lines = [
        "## ⚠️ Complexity Hotspots (Understand Before Touching)",
        "",
        "| Function | File | Direct Callers | Blast Radius |",
        "|---|---|---|---|",
    ]
    for h in plan.hotspots:
        lines.append(
            f"| `{h.name}` | `{h.file}:{h.line_start}` | {h.caller_count} | {h.blast_radius} |"
        )
    return "\n".join(lines)


def _render_safe_zones(plan: OnboardPlan) -> str:
    if not plan.safe_zones:
        return ""
    lines = [
        "## ✅ Safe Zones (Start Contributing Here)",
        "",
        "| Module | Dead Code % | Test Surface % |",
        "|---|---|---|",
    ]
    for z in plan.safe_zones[:5]:
        lines.append(f"| **{z.lobe}** | {z.dead_code_pct:.1f}% | {z.test_surface:.1f}% |")
    return "\n".join(lines)


def _render_things_to_know(plan: OnboardPlan) -> str:
    lines = ["## ⚠️ Things to Know"]
    if not plan.memories_available:
        lines += [
            "",
            "_No memory store found. Attach warnings and decisions to neurons:_",
            "",
            "```",
            'cerebrofy memory add "Clock skew breaks token expiry" \\',
            "    --type warning --neuron auth/tokens.py::validate_token",
            "```",
        ]
    elif not plan.things_to_know:
        lines += [
            "",
            "_No warnings or decisions recorded yet. Run `cerebrofy memory add` to start._",
        ]
    else:
        lines.append("")
        for title in plan.things_to_know:
            lines.append(f"- {title}")
    return "\n".join(lines)


def _render_footer(plan: OnboardPlan) -> str:
    return (
        f"---\n"
        f"_Generated by `cerebrofy onboard` — depth: {plan.depth}_\n"
        f"<!-- depth: {plan.depth} -->"
    )
